name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Run a one-line script
      working-directory: .
      run: |
        echo Hello, world!
        # cd ./hpsocket
        cd ../../..
        ls -R
        # cmake .
        # ls
        # make
    - uses: actions/checkout@v2
